version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: javax.servlet:javax.servlet-api
    versions:
    - "< 5, >= 4.a"
  - dependency-name: org.jboss.weld.servlet:weld-servlet
    versions:
    - "< 3, >= 2.a"
  - dependency-name: org.jboss.weld.servlet:weld-servlet-core
    versions:
    - 4.0.0.Final
  - dependency-name: org.jboss:jboss-parent
    versions:
    - "37"
  - dependency-name: org.codehaus.mojo:animal-sniffer-maven-plugin
    versions:
    - "1.19"
