language: java
jdk:
    - openjdk8
    - openjdk11

before_install:
  - sed -i.bak -e 's|http://repo.maven.apache.org/maven2|https://repo.maven.apache.org/maven2|g' $HOME/.m2/settings.xml

script:
    mvn clean install -P build-server

