:toc:

= Contributing Guide

Thank you in interest to contribute to the Arquillian Container Tomcat project!
We try to make it easy, and all contributions, even the smaller ones, are more than welcome.
This includes bug reports, fixes, documentation, etc.
First though, please read this page.

== Legal

All original contributions to Arquillian Container Tomcat project are licensed under the https://www.apache.org/licenses/LICENSE-2.0[ASL - Apache License], version 2.0 or later,
or, if another license is specified as governing the file or directory being modified, such other license.

All contributions are subject to the https://developercertificate.org/[Developer Certificate of Origin (DCO)].
The DCO text is also included verbatim in the [dco.txt](dco.txt) file in the root directory of the repository.

== Reporting an issue

This project uses https://github.com/arquillian/arquillian-container-tomcat/issues[GitHub Issues] for filing issues.

If you believe you found a bug, and it's likely possible, please indicate a way to reproduce it, what you are seeing and what you would expect to see.

== Before you contribute

To contribute, use GitHub Pull Requests, from your own fork.

Also, make sure you have set up your Git authorship correctly and your email address is associated with your GitHub account:

----
git config --global user.name "Your Full Name"
git config --global user.email your.email@example.com
----

If you use different computers to contribute, please make sure the name is the same on all your computers.

We use this information to acknowledge your contributions in release announcements.

== Setup

If you have not done so on this machine, you need to:

* Install Git and configure your GitHub access
* Install Java SDK 11 or higher (OpenJDK recommended)
