# Simple CI job that does `mvn clean install` on several JDKs
name: Arquillian Container Tomcat CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build project - JDK ${{matrix.java.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - { name: "11",
              java-version: 11,
          }
          - {
            name: "17",
            java-version: 17,
          }
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java.name }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java.java-version }}
      - name: "Build with Maven"
        run: |
          mvn clean install