name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        # Keep this list as: all supported LTS JDKs, the latest GA JDK, and optionally the latest EA JDK (if available).
        # Reference: https://adoptium.net/support/
        java:
          - 11
          - 17
          - 21
          - 24
          - 25-ea
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven using JDK ${{ matrix.java }}
        run: ./mvnw --batch-mode --no-transfer-progress verify
      - name: Upload Failsafe Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.java }}-failsafe-reports
          path: '**/target/failsafe-reports/*.xml'
